
grafana:
  enabled: true
  labels:
    instance: mgt-nv-eks
    datasource-mimir: enabled
    datasource-loki: enabled
    datasource-tempo: disabled

  datasources:
    mimir:
      enabled: true
      url: mimir.metrics.svc.cluster.local/prometheus
    
    loki:
      enabled: true
      url: loki.logging.svc.cluster.local
    
    tempo:
      enabled: true
      url: tempo.tracing.svc.cluster.local
