{{- if .Values.grafana.enabled -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    {{- $.Values.grafana.labels | toYaml | nindent 4 }}
spec:
  deployment:
    spec:
      replicas: 1
  config:
    log:
      mode: "console"
    security:
      admin_user: admin
      admin_password: grafana
{{- end -}}
